server:
  port: 3000

pig:
  auth:
    clientId: pig
    clientSecret: pig
    scope: server
    
ribbon:
  Httpclient:
    enable: false
  OkHttp:
    enable: true
  ReadTimeout: 30000
  ConnectTimeout: 30000
  
feign:
  okhttp:
    enable: true
  httpclient:
    enable: false
    
spring:
  redis:
    host: 192.168.40.250
    port: 6379
    password: redis
#加密参数
jasypt:
  encryptor:
    password: lengleng
    
logging:
  config: classpath:logback.xml

