server:
  port: 4050

spring:
  rabbitmq:
    host: 192.168.40.250
    port: 5672
    username: rabbitmq
    password: rabbitmq

sms:
  aliyun:
    accessKey: accessKey
    secretKey: secretKey
    channels:
      loginCodeChannel: SMS_34630023