server:
  port: 6001
  context-path: /accounts

#name: zhangxd

eureka:
  instance:
    metadata-map:
      user.name: ${security.user.name}
      user.password: ${security.user.password}

security:
  user:
    name: user
    password: password
  #oauth2:
    #client:
      #clientId: account-service
      #clientSecret: account-service
      #accessTokenUri: http://${authserver.hostname}:${authserver.port}${authserver.contextPath}/oauth/token
      #grant-type: client_credentials
      #scope: server

spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/springboot?useUnicode=true&characterEncoding=UTF-8
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      validation-query: SELECT 1 FROM DUAL
      min-evictable-idle-time-millis: 100000
  #jpa:
    #show-sql: true

#customer 
db:
  type: mysql