server:
  port: 4050

spring:
  rabbitmq:
    host: 192.168.40.250
    port: 5672
    username: rabbitmq
    password: rabbitmq

sms:
  aliyun:
    accessKey: ENC(Lm4sMaa8jpGOwK9hkuRI3SWHlUd63RTq)
    secretKey: ENC(A9i34tFkZLy8HVd9TTKjmnp5P/OE6pEE6+lAOF6tKxwPHizQ3/AG4cG+XoM8/5fO)
    channels:
      loginCodeChannel: SMS_34630023