server:
  port: 3000
  
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://192.168.40.140:3306/pig?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
pig:
  auth:
    clientId: pig
    clientSecret: pig
    scope: server

urls:
  anon:
    - /health
    - /social
    - /mobile/token

logging:
  config: classpath:logback.xml

