server:
  port: 5002

spring:
  sleuth:
    enabled: false
  rabbitmq:
    host: 192.168.40.250
    port: 5672
    username: rabbitmq
    password: rabbitmq

zipkin:
  storage:
    type: elasticsearch
    elasticsearch:
      hosts: 106.14.69.75:9201
      cluster: elasticsearch
      index: zipkin
      max-requests: 64
      index-shards: 5
      index-replicas: 1